<TABLE>
<TR>
	<TD>
		<?PHP
ECHO "NAME :  ";
ECHO $_POST ['NAME']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "SURNAME :  ";
ECHO $_POST ['SURNAME']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "EMAIL :  ";
ECHO $_POST ['EMAIL']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "NUMBER 1 :  ";
 ECHO $_POST ['N1']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "NUMBER 2 :  ";
ECHO $_POST ['N2']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "AGE :  ";
ECHO $_POST ['AGE']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "AGE GROUP :  ";
ECHO $_POST ['S1']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "D-O-B :  " ;
ECHO $_POST ['DOB']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "GENDRE :  ";
echo $_POST ['gender']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "ADDRESS :  ";
ECHO $_POST ['AEE']."<BR>" ;
	?>
	</TD>
</TR>
<TR>
	<TD>
		<?PHP
ECHO "BLOOD GROUP : " ;
ECHO $_POST ['S2']."<BR>" ;
	?>
	</TD>
</TR>
</TABLE>
